project:
  type: book
  output-dir: ../../_build/elixir-v3
  
book:
  title: "Elixir V3 (Legacy)"
  author: "FLUX:: Immersive"
  date: "2/6/2023"
  downloads: [pdf]
  chapters:
    - index.qmd
    - Introduction.qmd
    - About_True_Peak.qmd
    - Installation.qmd
    - Authorization.qmd
    - User_interface.qmd
    - Technical_Details.qmd
  appendices:
    - ../flux_processing_release_notes.qmd


format:
  html:
    theme: cosmo
    default-image-extension: gif
  pdf:
    documentclass: scrreport
    default-image-extension: png
    include-in-header: ../fluxtemplate.tex
