project:
  type: book
  output-dir: ../../_build/studio-session-plugins

book:
  title: "Studio Session Plugins"
  author: "FLUX:: Immersive"
  date: "2/6/2023"
  downloads: [pdf]
  chapters:
  - index.qmd
  appendices:
    - ../flux_processing_release_notes.qmd

format:
  html:
    theme: cosmo
    default-image-extension: gif
  pdf:
    documentclass: scrreport
    default-image-extension: png
    include-in-header: ../fluxtemplate.tex
