project:
  type: book
  output-dir: ../../_build/studio-session-plugins

book:
  title: "Studio Session Plugins"
  author: "FLUX:: Immersive"
  date: "2/6/2023"
  downloads: [pdf]
  chapters:
  - index.qmd
  appendices:
    - ../flux_processing_release_notes.qmd

metadata-files: 
  - ../_common.yaml