project:
  type: book
  output-dir: ../../_build/ircam-verb
  
book:
  title: "IRCAM Verb"
  chapters:
    - index.qmd
    - Quick_start_guide.qmd
    - Decay.qmd
    - Time_Structure_Display.qmd
    - Options.qmd
    - Time_Structure_Settings.qmd
    - Input_Output_Section.qmd
    - text: Preset Management
      href: ../generic_Preset_Management.qmd
    - text: Preset Manager
      href: ../generic_Preset_Manager.qmd
    - Credits.qmd
    - text: Specifications
      href: ../generic_specifications.qmd
  appendices:
    - ../flux_processing_release_notes.qmd

metadata-files: 
  - ../_common.yaml