project:
  type: book
  output-dir: ../../_build/ircam-verb
  
book:
  title: "IRCAM Verb"
  author: "FLUX:: Immersive"
  date: "2/6/2023"
  downloads: [pdf]
  chapters:
    - index.qmd
    - Quick_start_guide.qmd
    - Decay.qmd
    - Time_Structure_Display.qmd
    - Options.qmd
    - Time_Structure_Settings.qmd
    - Input_Output_Section.qmd
    - Preset_Section.qmd
    - Preset_Management.qmd
    - Credits.qmd
    - Specifications.qmd
  appendices:
    - ../flux_processing_release_notes.qmd

format:
  html:
    theme: cosmo
    default-image-extension: gif
  pdf:
    documentclass: scrreport
    default-image-extension: png
    include-in-header: ../fluxtemplate.tex
