docSection: "Immersive"
docSubsection: ""

project:
  type: book
  output-dir: ../../_build/ircam-hear ####### <=========== Don't forget to edit path if renaming is needed. YAML don't support concatenation

book:
  title: "IRCAM HEar"
  author: "FLUX:: Immersive"
  date: "2/6/2023"
  downloads: [pdf]
  chapters:
    - index.qmd
    - Concepts.qmd
    - Controls.qmd
    - Credits.qmd
    - References.qmd
    - Specifications.qmd

#[Release Notes](../../flux_processing_release_notes.md)


format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport