project:
  type: book
  output-dir: ../../_build/ircam-hear

book:
  title: "IRCAM HEar"
  chapters:
    - index.qmd
    - Concepts.qmd
    - Controls.qmd
    - Credits.qmd
    - References.qmd
    - text: Specifications
      href: ../generic_specifications.qmd
  appendices:
    - ../flux_processing_release_notes.qmd
    
metadata-files: 
  - ../_common.yaml