project:
  type: book
  output-dir: ../../_build/ircam-hear

book:
  title: "IRCAM HEar"
  author: "FLUX:: Immersive"
  date: "2/6/2023"
  downloads: [pdf]
  chapters:
    - index.qmd
    - Concepts.qmd
    - Controls.qmd
    - Credits.qmd
    - References.qmd
    - Specifications.qmd
  appendices:
    - ../flux_processing_release_notes.qmd

format:
  html:
    theme: cosmo
    default-image-extension: gif
  pdf:
    documentclass: scrreport
    default-image-extension: png
    include-in-header: ../fluxtemplate.tex