project:
  type: book
  output-dir: ../../_build/evo-touch

book:
  title: "Evo Touch"
  chapters:
    - index.qmd
    - General_Settings.qmd
    - Module_Settings.qmd
    - Geek_Settings.qmd
    - Plugin_Settings.qmd
    - text: Preset Management
      href: ../generic_Preset_Management.qmd
    - text: Preset Manager
      href: ../generic_Preset_Manager.qmd
    - text: Specifications
      href: ../generic_specifications.qmd
    - Credits.qmd
  appendices:
    - ../flux_processing_release_notes.qmd

metadata-files: 
  - ../_common.yaml