## Additional libs

+ GS lib  Emmanuel Julien, Gael Martinet (Copyright 2013 Emmanuel Julien)
+ ThorVG, Copyright (c) 2020 - 2023 notice for the ThorVG Project (see AUTHORS)
+ r8brain free - Copyright (c) 2013-2023 Aleksey Vaneev
+ LibJpeg - Copyright (c) 1991-2016, Thomas G. Lane, Guido Vollbeding
+ libpng :
  + Copyright (c) 1995-2023 The PNG Reference Library Authors. 
  + Copyright (c) 2018-2023 Cosmin Truta. 
  + Copyright (c) 2000-2002, 2004, 2006-2018 Glenn Randers-Pehrson. 
  + Copyright (c) 1996-1997 Andreas Dilger. 
  + Copyright (c) 1995-1996 Guy Eric Schalnat, Group 42, Inc.

+ Freetype 2 - Copyright (c) 2006-2023 by David Turner, Robert Wilhelm, and Werner Lemberg.
+ Zlib - Copyright (c) 1995-2022 Jean-loup Gailly and Mark Adler
+ bzip2 - Copyright (c) 1996-2010 Julian Seward <jseward@bzip.org>
+ Boost - BSL-1.0
+ ni-media - Copyright (c) 2022 Native Instruments
+ pfft:
  + Copyright (c) 2004 the University Corporation for Atmospheric Research ("UCAR")
  + Copyright (c) 2013  Julien Pommier ( pommier@modartt.com )
  + Copyright (c) 2019  Hayati Ayguen ( h_ayguen@web.de )
  + Copyright (c) 2020  Dario Mambro ( dario.mambro@gmail.com )

+ pybind11 - Copyright (c) 2016 Wenzel Jakob <wenzel.jakob@epfl.ch>
+ rtaudio - Copyright (c) 2001-2021 Gary P. Scavone
+ rtmidi - Copyright (c) 2003-2021 Gary P. Scavone
+ concurrentqueue - Copyright (c) 2013-2016, Cameron Desrochers.
+ readerwriterqueue - Copyright (c) 2013-2021, Cameron Desrochers.
+ assimp - Copyright (c) 2006-2021, assimp team
+ enet - Copyright (c) 2002-2020 Lee Salzman
+ fmt - Copyright (c) 2012 - present, Victor Zverovich and {fmt} contributors
+ functions (Erik Rigtorp) - Copyright (c) 2015 Erik Rigtorp <erik@rigtorp.se>
+ inplace_function - BSL-1.0
+ gtest - Copyright 2008, Google Inc.
+ jsoncpp - Copyright (c) 2007-2010 Baptiste Lepilleur and The JsonCpp Authors
+ libcurl - Copyright (c) 1996 - 2023, Daniel Stenberg, daniel@haxx.se, and many contributors
+ magic_enum - Copyright (c) 2019 - 2023 Daniil Goncharov
+ nanobench - Copyright (c) 2019-2023 Martin Leitner-Ankerl
+ nlohmann_json - Copyright (c) 2013-2022 Niels Lohmann
+ openddl - Copyright (c) 1999-2022 Eric Lengyel
+ openvr - Copyright (c) 2015, Valve Corporation
+ poly2tri - Copyright (c) 2009-2018, Poly2Tri Contributors
+ pugixml - Copyright (c) 2006-2022 Arseny Kapoulkine
+ rapidjson - Copyright (c) 2015 THL A29 Limited, a Tencent company, and Milo Yip.
+ shared_recursive_mutex - Copyright (c) 2019 konanM
+ sentry-native - Copyright (c) 2019 Sentry (https://sentry.io) and individual contributors.
+ sqlite3 - Public Domain License
+ sqlite_orm - Copyright (c) 2012-2023 Eugene Zakharov and others
+ stb - Copyright (c) 2017 Sean Barrett
+ utfcpp - Copyright 2006 Nemanja Trifunovic
+ unqlite - Copyright (c) 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019 Symisc Systems, S.U.A.R.L [M.I.A.G + Mrad Chems Eddine <chm@symisc.net>].



