# Introduction
At first glance, an audio signal chain is very much like a series of black boxes. 
As an audio engineer, you can trust your ears and the manufacturer's data-sheets to assess the effects this chain has on the incoming audio. 
In a variety of cases, however, this is either simply impractical, not possible or not precise enough. 
Such situations include live sound setups, recording setups, etc., where unknown factors such as the venue's or studio's acoustic response are a crucial part of the chain.

It is therefore necessary to resort to scientific measurement procedures and tools to obtain precise, trustworthy and reproducible results. 
The main tools at your disposal for this purpose are transfer curve and impulse response measurement, which are especially designed for this task.

As with any measurement instrument, it is important to have a good grasp of its mode of operation as well as any possible limitations in order to use it most efficiently. 
Some knowledge of acoustic principles and notions of signal processing are naturally required as well. 
While this manual tries to cover most typical use cases and point out common do's and dont's, it obviously cannot replace neither a good textbook nor practical experience.
