# Practical considerations for capturing measurement signals

## Use a measurement microphone
The goal here is to take the measurement chain out of the equation, so only specially designed microphones that exhibit a flat curve, minimal coloration, lowest noise and distortion should be used.

## Choose a neutral preamplifier and calibrate it accurately
For the same reasons, select the most neutral preamplifier and A/D D/A convertors you have at your disposal. 
It is especially important to be able to set accurate and reproducible gain, linear and flat response. 
Take special care that the signal is not so hot as to clip or distort the preamplifier input stages, as this would distort the measurements accordingly and induce you into error.

## Maximize signal-to-noise ratio
When measuring an acoustic system, raise up the volume as high as practical for maximal signal-to-noise ratio, and try to minimize any spurious acoustic noises such as footsteps and conversation. 
As always, the goal is to set the test signal as high as possible above the noise floor while ensuring all devices still operate in their linear region. 
Finally, make sure the microphone is firmly held in position and acoustically decoupled from the floor.

In a live concert context, especially with the audience present, using a noise signal is not practical.
In this case you can still perform measurements, using a music signal, but the measurements will be less accurate as the signal isn't known in advance and does not necessarily contain all frequencies like noise does.


