docSection: "Processing"
docSubsection: ""

project:
  type: book
  output-dir: ../../_build/pure-dexpander ####### <=========== Don't forget to edit path if renaming is needed. YAML don't support concatenation

book:
  title: "Pure DExpander"
  author: "FLUX:: Immersive"
  date: "2/6/2023"
  downloads: [pdf]
  chapters:
  - index.qmd
  - General_Settings.qmd
  - Time_Related_Settings.qmd
  - Dynamic_Section_Settings.qmd
  - Display.qmd
  - Preset_Management.qmd
  - Specifications.qmd
    
#[Release Notes](../../flux_processing_release_notes.md)


format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport