project:
  type: book
  output-dir: ../../_build/evo-eq

book:
  title: "Evo EQ"
  chapters:
    - index.qmd
    - General_Settings.qmd
    - Module_Settings.qmd
    - Shortcuts.qmd
    - Plugin_Settings.qmd
    - Preset_Management.qmd
    - Preset_Manager.qmd
    - Specifications.qmd
    - Credits.qmd
  appendices:
    - ../flux_processing_release_notes.qmd

metadata-files: 
  - ../_common.yaml