docSection: "Processing"
docSubsection: ""

project:
  type: book
  output-dir: ../../_build/ircam-trax ####### <=========== Don't forget to edit path if renaming is needed. YAML don't support concatenation

book:
  title: "IRCAM Trax"
  author: "FLUX:: Immersive"
  date: "2/6/2023"
  downloads: [pdf]
  chapters:
    - index.qmd
    - part: Transformer.qmd
      chapters:
      - Mode.qmd
      - Source.qmd
      - Target.qmd
      - Remix.qmd
      - Filters.qmd
      - Options.qmd
      - Modulation.qmd
      - Spectral_Envelope.qmd
      - Main_Input_-_Output_Section.qmd
    - part: Cross_Synthesis_&_Source_Filter_Tools.qmd
      chapters:
      - Cross_Synthesis.qmd
      - Source_Filter.qmd
    - Preset_Section.qmd
    - Presets_Management.qmd
    - Credits.qmd
    - Specifications.qmd
    
#[Release Notes](../../flux_processing_release_notes.md)


format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport