docSection: "Processing"
docSubsection: ""

project:
  type: book
  output-dir: ../../_build/ircam-spat ####### <=========== Don't forget to edit path if renaming is needed. YAML don't support concatenation

book:
  title: "IRCAM Spat"
  author: "FLUX:: Immersive"
  date: "2/6/2023"
  downloads: [pdf]
  chapters:
    - index.qmd
    - part: Sources.qmd
      chapters:
      - Main_Section.qmd
      - Display.qmd
      - Perceptual_Factors_.qmd
      - Radiations.qmd
      - Axis_Omni_Filters.qmd
      - Options.qmd
      - Main_Input_-_Output_Section.qmd
    - part: Reverb.qmd
      chapters:
      - Main_Section2.qmd
      - Perceptual_Factors.qmd
      - Room_Response.qmd
      - Display2.qmd
      - Options2.qmd
      - Main_Input_-_Output_Section.qmd
    - part: Setup.qmd
      chapters:
      - Setup2.qmd
      - Routing.qmd
      - Stereo_Pair_Width_-_Subwoofer.qmd
      - Main_Input_-_Output_Section.qmd
    - Preset_Section.qmd
    - Preset_Management.qmd
    - Credits.qmd
    
#[Release Notes](../../flux_processing_release_notes.md)


format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport