project:
  type: book
  output-dir: ../../_build/pure-dcompressor

book:
  title: "Pure DCompressor"
  chapters:
  - index.qmd
  - General_Settings.qmd
  - Time_Related_Settings.qmd
  - Dynamic_Section_Settings.qmd
  - Display.qmd
  - Preset_Management.qmd
  - Specifications.qmd
  - Credits.qmd
  appendices:
    - ../flux_processing_release_notes.qmd

metadata-files: 
  - ../_common.yaml