project:
  type: book
  output-dir: ../../_build/pure-limiter
  
book:
  title: "Pure Limiter"
  chapters:
  - index.qmd
  - Plug-in_Settings.qmd
  - Specifications.qmd
  - Compatibility.qmd
  - Credits.qmd
  appendices:
    - ../flux_processing_release_notes.qmd

metadata-files: 
  - ../_common.yaml