project:
  type: book
  output-dir: ../../_build/evo-in ####### <=========== Don't forget to edit path if renaming is needed. YAML don't support concatenation

book:
  title: "Evo In"
  author: "FLUX:: Immersive"
  date: "2/6/2023"
  downloads: [pdf]
  chapters:
    - index.qmd
    - General_Settings.qmd
    - Module_Settings.qmd
    - Plugin_Settings.qmd
    - Specifications.qmd
  license: "Copyright Acme, Inc. 2021. All Rights Reserved"
#[Release Notes](../../flux_processing_release_notes.md)


format:
  html:
    theme: cosmo
    default-image-extension: gif
  pdf:
    documentclass: scrreprt
    default-image-extension: png
    include-in-header: header.tex
