project:
  type: book
  output-dir: ../../_build/evo-in ####### <=========== Don't forget to edit path if renaming is needed. YAML don't support concatenation

book:
  title: "Evo In"
  author: "FLUX:: Immersive"
  date: "2/6/2023"
  downloads: [pdf]
  chapters:
    - index.qmd
    - General_Settings.qmd
    - Module_Settings.qmd
    - Plugin_Settings.qmd
    - text: Specifications
      href: ../generic_specifications.qmd
    - Credits.qmd
  appendices:
    - ../flux_processing_release_notes.qmd


metadata-files: 
  - ../_common.yaml