project:
  type: book
  output-dir: ../../_build/elixir

book:
  title: "Elixir"
  author: "FLUX:: Immersive"
  date: "2/6/2023"
  downloads: [pdf]
  chapters:
    - index.qmd
    - Introduction.qmd
    - About_True_Peak.qmd
    - Installation_authorization.qmd
    - User_interface.qmd
    - Preferences.qmd
    - Specifications.qmd
  appendices:
    - ../flux_processing_release_notes.qmd


format:
  html:
    theme: cosmo
    default-image-extension: gif
  pdf:
    documentclass: scrreport
    default-image-extension: png
    include-in-header: ../fluxtemplate.tex
