project:
  type: book
  output-dir: ../../_build/elixir

book:
  title: "Elixir"
  chapters:
    - index.qmd
    - Introduction.qmd
    - About_True_Peak.qmd
    - Installation_authorization.qmd
    - User_interface.qmd
    - Preferences.qmd
    - text: Preset Management
      href: ../generic_Preset_Management.qmd
    - text: Preset Manager
      href: ../generic_Preset_Manager.qmd
    - text: Specifications
      href: ../generic_specifications.qmd
    - Credits.qmd
  appendices:
    - ../flux_processing_release_notes.qmd

metadata-files: 
  - ../_common.yaml