# Studio Session Analyser

## Welcome

Thank you for purchasing the Studio Session Plugins (bundle) which includes the **Studio Session Analyser**

The Studio Session Analyser is a light version of our renowned  [FLUX:: Real Time Analyzer System](../analyser_doc/00_Pure_Analyzer_00_Pure_Analyzer.md)

The Session Analyser is installed as a single application. It has the same basic functioning as with the standard FLUX:: Analyser with the following limitations;


* Inputs & Outputs : Mono / Stereo
* I/O Configuration: SampleGrabber Plug-in Only (no hardware I/O)
* Max 96kHz sample rate. 44.1, 48, 88.2, 96
* No Support for any add-on options

:::{.callout-note}
Please note that the Studio Session Pack license is a bundle license and the Studio Session Analyzer can only be used on the same computer as the rest of the plug-ins in the bundle are used.
:::


## User documentation

Please refer to the **[FLUX:: Real Time Analyzer System](../analyser_doc/00_Pure_Analyzer_00_Pure_Analyzer.md)** user documentation.

...

