project:
  type: book
  output-dir: ../../_build/alchemist
  
book:
  title: "Alchemist"
  chapters:
    - index.qmd
    - part: General_Settings_and_Display.qmd
      chapters:
      - General_Settings.qmd
      - General_Display.qmd
    - part: Bands_Settings_and_Display.qmd
      chapters:
      - Band_Settings.qmd
      - Time_Related_Settings.qmd
      - Band_Display.qmd
    - part: Dynamic_Sections_Settings_and_Display.qmd
      chapters:
      - Dynamic_Sections_Settings.qmd
      - Dynamic_Sections_Display.qmd
    - text: Preset Management
      href: ../generic_Preset_Management.qmd
    - text: Preset Manager
      href: ../generic_Preset_Manager.qmd
    - text: Specifications
      href: ../generic_specifications.qmd
    - Credits.qmd
  appendices:
    - ../flux_processing_release_notes.qmd
    
metadata-files: 
  - ../_common.yaml