# Autonomous mobile configuration
## Capture
* Required:
    * Entry-level laptop.
    * Sound card with at least one stereo input available.
    * Basic DAW software for SampleGrabber signal capture, capable of using of one of the
    supported plugin formats.
    * Network connection.

* Optional:
    * Phantom-powered microphone input for capturing room signal in performing room acoustics
    measurements (Transfer function and impulse response).
    * Wireless network connection.


:::{.callout-warning}
 **IMPORTANT!** - The Pure Analyzer Studio Session supports audio input only by using the plug-in. 
No hardware input/output options are supported for the Pure Analyzer Session.
:::

## Analysis

Mid-range desktop with an OpenGL/DirectX capable graphics card that
meets the minimum [System requirements](18_System_Requirements_00_System_requirements.md).

Capture and analysis can naturally be performed on the same machine, although you can also couple
the system with a wireless transmitter to route a source test signal to the laptop in order to
perform transfer curve measurements at different locations more conveniently.