# Usage

## Snapshots
Any number of snapshots can be stored and recalled for further use, and are organized into a group container called a project.

Please keep in mind computing and displaying the data associated with a snapshot is not free in terms of processing power and memory.
How many snapshots you can use at a time will depends on your particular configuration.

## Project
FLUX:: Analyzer creates a default project at startup, which the snapshots will be added to.
Projects are stored on disk as a folder containing associated data files. Projects can therefore be renamed, moved, archived and transferred between computers using any method you wish, provided you include all data files inside the project folder.

You can save and reload as many projects as you want, disk space permitting.

>Projects are saved in

`<User folder>/FLUX SE/Pure Analyzer System/Data/<Project Name>`
>

<!-- LIVEVERSION-->
<!-- TODO: Rename??? What is not clear is the project management within the Analyzer -->
