# System requirements

FLUX:: Analyzer is built around FLUX::SE's new 2D/3D efficient graphic engine, which employs full GPU-acceleration using an OpenGL-compliant graphics card.

In order to experience the outstanding responsiveness with the Analyzer, even with a very busy display, and to fully take advantage of the software's analysis capabilities, using a modern nVidia or ATI Radeon
graphics card is recommended.

Older, and other less efficient graphics cards do not have the required performance and specifications, and offload too much work to the CPU (see below).

The processor is also an important factor, and we recommend using at least and Intel Core 2 Duo, Core i5 or newer architecture processor.
AMD processors are also supported, but might exhibit lower performance, as they do not offer the same capabilities and optimizations as Intel CPUs.

## Minimum requirements

* CPU: Intel Core 2 Duo.
* GPU: OpenGL 2.0 or superior compatible, with pixel-shader support.

## Recommended configuration
CPU: Intel Core i5 or better.

GPU: AMD/ATI Radeon or nVidia video-card. Intel integrated graphics are not powerful enough and should be avoided.

## Common requirements
A free USB port to connect the iLok key if not using machine authorization

:::{.callout-note}
Please check the latest version of vendor-provided, optimized drivers are installed for your graphics card. Generic drivers are generally less up-to-date and may contain bugs or miss optimizations present in drivers specific to your particular model.
:::
<!-- TODO: To review-->

## Compatibility
FLUX:: Analyzer is a 64bit application fully compatible with 64-bit operating systems.

### Operating Systems

* PC: Windows 10
* Apple: macOS versions 10.13 and up (macOS Big Sur, Monterey compliant, Compatible with ARM / Silicon)

### Hardware IO support
Any soundcard with a driver compliant with these standards:

* ASIO(Windows).
* Core Audio (macOS).

###  Software - Sample Push support

SampleGrabber is a 32-bit plug-in compatible using 64-bit double precision internal processing, compatible with 32-bit and 64-bit (via bridge) hosts

All major native formats (AAX, VST, AU, RTAS, TDM, AAX VENUE) are supported.

### Supported formats
* Windows 10
    * VST (2.4)
    * RTAS*
    * TDM*
    * AAX
    * AAX VENUE

* macOS - 10.12 and later
    * VST (2.4)
    * AU
    * AAX
    * RTAS*
    * TDM*

:::{.callout-warning}
*The TDM/RTAS version requires ProTools version 7 or above.
:::
<!-- TODO: To review when native ARM, -->
