# Test signals
Pure Analyzer is designed to cover the broadest range of practical use cases, and does not impose a limitation on the measurement signal used.

Traditionally, transfer curve and impulse response measurements are performed by feeding a specially designed test signal into the system, the most commonly employed being pink and white noise and swept sines. 
While these type of signals are those that give the best and more accurate results, with each having its own strength and weaknesses, they do prohibit the measurement of a system in the context of a live system with the audience present.

Performing measurements using a live music signal allows the engineer to fine tune the system settings to compensate for changing conditions such as the effect of the crowd on acoustic reflections and damping, varying temperature and humidity, etc. 
Although less pleasing to the ear, we do however recommend using a noise test signal whenever possible, at least as a starting point.

You are free to use any kind of test signal generator, outboard or plugin, provided you trust it being reliable and easy to use. 
A selection of plugins suitable for this task is shown in the chart below.

> While Pure Analyzer does not impose any limitation on the test signal used, we recommend using the integrated [Signal generator](12_Signal_generator_01_Signal_types.md), which has been especially designed for this task. We conducted thorough tests on a wide panel of signal generators available as plugins or integrated into DAW software and found that many do not meet the requirements for performing accurate and reliable measurements.

