# Introduction
The transfer function of a system measures its frequency response, which is expressed in terms of magnitude and phase response.
The transfer function measures the way the system affects the magnitude and phase of an incoming signal at different frequencies, and is essentially a ratio of output versus input spectra.

Practical uses of this are numerous: determining the curve of an equalizer, determining what frequencies are emphasized by an outboard device, measuring a room's acoustic response, etc.

:::{.callout-note}
The transfer function assumes the system meets the following conditions:
linearity

time-invariance

Linearity notably implies the system is free of distortion, and time-invariance that its characteristics do not change in time.

Failing to meet these requirements will lead to unpredictable results.

In practice, the transfer function is considered an adequate measurement technique for most real-world systems, except for devices exhibiting highly non-linear behaviour such as compressors and distortion effects, and time-modulation based effects such as chorus and flanger.
:::