project:
  type: book
  output-dir: ../../_build/bittersweet
  
book:
  title: "Bittersweet"
  chapters:
    - index.qmd
    - Credits.qmd
  appendices:
    - ../flux_processing_release_notes.qmd

metadata-files: 
  - ../_common.yaml