project:
  type: book
  output-dir: ../../_build/evo-channel

book:
  title: "Evo Channel"
  chapters:
    - index.qmd
    - General_Settings.qmd
    - Module_Settings.qmd
    - Geek_Settings.qmd
    - Plugin_Settings.qmd
    - Shortcuts.qmd
    - Preset_Management.qmd
    - Preset_Manager.qmd
    - Specifications.qmd
  appendices:
    - ../flux_processing_release_notes.qmd

metadata-files: 
  - ../_common.yaml