# Specifications

## Availability

LevelMagic(TM) is available in the following configurations:

- Native Mono/Stereo - AU / VST / AAX Native / AAX AudioSuite
- Add-on Option: Native Multichannel 5.1 - AU / VST / AAX Native / AAX AudioSuite

## Processing Specifications

- 64-bits internal floating point processing.
- Sampling rates in 44.1, 48, 88.2 and 96 KHz
- Audio I/O in Mono, Stereo and Multichannel 5.

## Compatibility

All major native formats are supported.

### Windows - Vista, 7 and 8 all in both 32 and 64 bits*. (XP v.2.4 / 32 bit only)

- VST (2.4)
- AAX Native*
- AAX AudioSuite*

### Mac OS X (Intel) - 10.7, 10.8 and 10.9 in both 32 and 64 bits*.

- VST (2.4)
- AU
- AAX Native*
- AAX AudioSuite*

##Software Licence Requirements

In order to use the software one of the following alternatives is required

- An ilok.com user account and an iLok USB Smart Key. More information: [http://www.ilok.com/](http://www.ilok.com/)
- A Flux:: USB Dongle (Available in our online store).

## More Information

For more information about LevelMagic(TM) and the rest of our product line, visit our website: [http://flux.audio/](http://flux.audio/)

* LevelMagic(TM) AAX Native & AAX AudioSuite supports 32 bit in Pro Tools 10.3.5 and 64 bit in Pro Tools 11.

