---
title: "FLUX:: Documentation"
---

## Immersive

 - [SPAT Revolution](spat-revolution/index.html)
 - [Ircam HEar](ircam-hear/index.html)

## Analysis

 - [FLUX:: Analyzer](anaylzer/index.html)
 - [Studio Session Analyzer](/studio-session-analyser/index.html)

## Evo Modules

 - [Evo Channel](/evo-channel/index.html)
 - [Evo In](/evo-in/index.html)
 - [Evo EQ](/evo-eq/index.html)
 - [Evo Compressor](/evo-comp/index.html)
 - [Evo Touch](/evo-touch/index.html)

## Processing

 - [Alchemist](/alchemist/index.html)
 - [Bittersweet](/bittersweet/index.html)
 - [Bittersweet Pro](/bittersweet-pro/index.html)
 - [Elixir](/elixir/index.html)
 - [Epure](/epure/index.html)
 - [Ircam Trax](/ircam-trax/index.html)
 - [Ircam Verb](/ircam-verb/index.html)
 - [Ircam Verb Session](/ircam-verb-session/index.html)
 - [Pure Compressor](/pure-compressor/index.html)
 - [Pure Dcompressor](/pure-dcompressor/index.html)
 - [Pure Dexpander](/pure-dexpander/index.html)
 - [Pure Expander](/pure-expander/index.html)
 - [Pure Limiter](/pure-limiter/index.html)
 - [Solera](/solera/index.html)
 - [Stereo Tool](/stereotool/index.html)
 - [Studio Session Plugins](/studio-session-plugins/index.html)
 - [Syrah](/Syrah/index.html)
 
## Legacy

- [Elixir v3](/elixir-v3/index.html)
- [Ircam Spat (Plugin)](/ircam_spat/index.html)
- [Jünger Level Magic](/junger-level-magic/index.html)
