project:
  type: book
  output-dir: ../../_build/epure
  
book:
  title: "Epure"
  chapters:
    - index.qmd
    - Special_Functions.qmd
    - Setup_-_Input_Routing_-_MS_Encode_Decode_-_Groups.qmd
    - text: Preset Management
      href: ../generic_Preset_Management.qmd
    - text: Preset Manager
      href: ../generic_Preset_Manager.qmd
    - text: Specifications
      href: ../generic_specifications.qmd
    - Compatibility.qmd
    - Credits.qmd
  appendices:
    - ../flux_processing_release_notes.qmd

metadata-files: 
  - ../_common.yaml