# SPAT Revolution - Credits

## User Guide and Documentation

**Cristian Vogel, Hugo Larin, Jean-Loup Pecquais and Nicolas Erard**

**Additional contributions:**
Gaël Martinet, Vincent Carlier, Florie-Anne Lafaye, Thibaut Carpentier, Anders Tveit and the IRCAM team.

### Project Manager and Designer:
Gaël Martinet, Hugo Larin

### Application Development:
Gaël Martinet, Florie-Anne Lafaye, Alexis Gentil, Nicolas Erard, Siegfried Hand and Antoine Lorence.

### FLUX:: DSP Design and Development:
Gaël Martinet, Maxence Grandidier and Lorcan Mc Donagh

### IRCAM "Spat~" Design of digital signal processing algorithms and implementation in Max:
Jean-Marc Jot (Espaces Nouveaux / Ircam).

### IRCAM "Spat~" Objective and perceptual characterization of room acoustical quality:
Jean-Pascal Jullien, Olivier Warusfel and Eckhard Kahle

**Additional contributions:**

Gerard Assayag, Georges Bloch, Martine Marin, Véronique Larcher, Guillaume Vandernoot, Khoa-Van Nguyen and Markus Noisternig

### IRCAM "Spat~" C++ dsp code:
Thibaut Carpentier and Remy Muller

### Graphic design:
Nicolas Philippot and Gaël Martinet

### FLUX:: Framework development:
Gaël Martinet, Florie-Anne Lafaye, Lorcan Mc Donagh, Alexis Gentil, Bastien Prevosto, Anthony Belard, Siegfried Hand and Antoine Lorence

**Additional contributions:**
Vincent Carlier, Jean-Loup Pecquais, Nicolas Erard, Jean Cruypenynck, Pablo Arias, Samuel Tracol, Olivier Nemoz

### FLUX:: Framework graphic engine:
Emmanuel Julien (GS lib) and Gaël Martinet

### Translation
* French: Jean-Loup Pecquais, Nicolas Erard
* German: Nils Hahmann
* Korean: Gong Eunju, Kim Joohna
* Italian: Gianni Tamanini
* Spanish: Ralph Killhertz


### Additional libs:
* GS lib (Emmanuel Julien, Gael Martinet)
* ThorVG, Copyright (c) 2020 - 2023 notice for the ThorVG Project (see AUTHORS)
* r8brain free - Copyright (c) 2013-2023 Aleksey Vaneev
* LibJpeg - Copyright (c) 1991-2016, Thomas G. Lane, Guido Vollbeding
* libpng :
    - Copyright (c) 1995-2023 The PNG Reference Library Authors.
    - Copyright (c) 2018-2023 Cosmin Truta.
    - Copyright (c) 2000-2002, 2004, 2006-2018 Glenn Randers-Pehrson.
    - Copyright (c) 1996-1997 Andreas Dilger.
    - Copyright (c) 1995-1996 Guy Eric Schalnat, Group 42, Inc.

* Freetype 2 - Copyright (c) 2006-2023 by David Turner, Robert Wilhelm, and Werner Lemberg.
* Zlib - Copyright (c) 1995-2022 Jean-loup Gailly and Mark Adler
* bzip2 - Copyright (c) 1996-2010 Julian Seward <jseward@bzip.org>
* Boost - BSL-1.0
* mimalloc - Copyright (c) 2018-2021 Microsoft Corporation, Daan Leijen
* ni-media - Copyright (c) 2022 Native Instruments
* pfft:
    - Copyright (c) 2004 the University Corporation for Atmospheric Research ("UCAR")
    - Copyright (c) 2013  Julien Pommier ( pommier@modartt.com )
    - Copyright (c) 2019  Hayati Ayguen ( h_ayguen@web.de )
    - Copyright (c) 2020  Dario Mambro ( dario.mambro@gmail.com )

* pybind11 - Copyright (c) 2016 Wenzel Jakob <wenzel.jakob@epfl.ch>
* rtaudio - Copyright (c) 2001-2021 Gary P. Scavone
* rtmidi - Copyright (c) 2003-2021 Gary P. Scavone
* concurrentqueue - Copyright (c) 2013-2016, Cameron Desrochers.
* readerwriterqueue - Copyright (c) 2013-2021, Cameron Desrochers.
* assimp - Copyright (c) 2006-2021, assimp team
* enet - Copyright (c) 2002-2020 Lee Salzman
* fmt - Copyright (c) 2012 - present, Victor Zverovich and {fmt} contributors
* functions (Erik Rigtorp) - Copyright (c) 2015 Erik Rigtorp <erik@rigtorp.se>
* inplace_function - BSL-1.0
* gtest - Copyright 2008, Google Inc.
* jsoncpp - Copyright (c) 2007-2010 Baptiste Lepilleur and The JsonCpp Authors
* libcurl - Copyright (c) 1996 - 2023, Daniel Stenberg, daniel@haxx.se, and many contributors
* magic_enum - Copyright (c) 2019 - 2023 Daniil Goncharov
* nanobench - Copyright (c) 2019-2023 Martin Leitner-Ankerl
* nlohmann_json - Copyright (c) 2013-2022 Niels Lohmann
* openddl - Copyright (c) 1999-2022 Eric Lengyel
* openvr - Copyright (c) 2015, Valve Corporation
* poly2tri - Copyright (c) 2009-2018, Poly2Tri Contributors
* pugixml - Copyright (c) 2006-2022 Arseny Kapoulkine
* rapidjson - Copyright (c) 2015 THL A29 Limited, a Tencent company, and Milo Yip.
* shared_recursive_mutex - Copyright (c) 2019 konanM
* sentry-native - Copyright (c) 2019 Sentry (https://sentry.io) and individual contributors.
* sqlite3 - Public Domain License
* sqlite_orm - Copyright (c) 2012-2023 Eugene Zakharov and others
* stb - Copyright (c) 2017 Sean Barrett
* utfcpp - Copyright 2006 Nemanja Trifunovic
* unqlite - Copyright (c) 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019 Symisc Systems, S.U.A.R.L [M.I.A.G Mrad Chems Eddine <chm@symisc.net>].

### Additional Python modules:
* sourcedefender - Copyright (c) 2018-2024 SOURCEdefender. All rights reserved.
* RTTrPM SDK (Blacktraxx) Copyright (c) 2019 CAST Group of Companies Inc
* argh (Andrey Mikhaylenko) - Copyright © 2010—2023 Andrey Mikhaylenko and contributors
* chardet (Mark Pilgrim, Daniel Blanchard)
* charset_normalizer - Copyright (c) 2019 TAHRI Ahmed R.
* docopt (Vladimir Keleshev) - Copyright (c) 2012 Vladimir Keleshev, <vladimir@keleshev.com>
* dotenv - Copyright (c) 2014, Saurabh Kumar
* ecdsa (Peter Pearson) - Copyright (c) 2010 Brian Warner
* environs (Steven Loria) - Copyright 2022 Steven Loria
* ftputil (Stefan Schwarzer) - Stefan Schwarzer <sschwarzer@sschwarzer.net> and others contributors
* numpy - Copyright (c) 2005-2023, NumPy Developers.
* pendulum - Copyright (c) 2015 Sébastien Eustace
* psutil (Giampaolo Rodola) - Copyright (c) 2009, Jay Loden, Dave Daeschler, Giampaolo Rodola
* watchdog:
    - Copyright 2010 Malthe Borch <mborch@gmail.com>
    - Copyright 2011 Yesudeep Mangalapilly <yesudeep@gmail.com>Copyright 2012 Google, Inc & contributors.
* tgcrypto - Copyright (c) 2017-2020 Dan <https://github.com/delivrance>
* idna - Copyright (c) 2013-2022, Kim Davies and contributors. All rights reserved.
* marshmallow - Copyright 2021 Steven Loria and contributors
* packaging - Copyright (c) Donald Stufft and individual contributors.
* paramiko (Jeff Forcier) - Copyright (c) 2003-2008  Robey Pointer <robeypointer@gmail.com>
* pathtools Copyright (c) 2010 by Yesudeep Mangalapilly
* ptvsd (Microsoft) - Copyright (c) Microsoft Corporation.  All rights reserved.
* pyga (Arun K.R.)
* pylightxl - Copyright (c) 2019 Viktor Kis
* pyparsing - Copyright (c) 2003-2019  Paul T. McGuire
* pytzdata - Copyright (c) 2015 Sébastien Eustace
* winshell (Tim Golden) - Copyright (c) 2012 Tim Golden
* six - Copyright (c) 2010-2020 Benjamin Peterson
* Request (Kenneth Reitz)
* sentry_sdk - Copyright (c) 2018 Functional Software, Inc. dba Sentry
* urllib3 - Copyright (c) 2008-2020 Andrey Petrov and contributors
* certifi (Kenneth Reitz)
* anytree (c0fec0de)
* boltons - Copyright (c) 2013, Mahmoud Hashemi
* msgpack (Inada Naoki) - Copyright (c) 2008-2011 INADA Naoki <songofacandy@gmail.com>
* dateutil - Copyright 2017- Paul Ganssle <paul@ganssle.io> and dateutil contributors
* PyYAML (Kirill Simonov)


### And
thanks to all fantastic testers...


### FLUX:: Special Thanks to:
Alain, Yves, Bruno and Claude for helping to shape our minds over the years.


### Published by FLUX::
```
http://wwww.flux.audio
Copyright (c) 2024 HARMAN International, All rights reserved.
FLUX:: is a trademark of HARMAN International.
"SPAT Revolution" Copyright (c) 2024 HARMAN International. All rights reserved.

Spatialisateur and "Spat~" are trademarks of Ircam and Espaces Nouveaux:

The Ambisonic Logo, a trademark formerly owned by Wyastone Estade Ltd, which expired
in 2010 is featured on page 30 of this guide
```

### FLUX::
http://wwww.flux.audio

COPYRIGHT (c) 2024, HARMAN INTERNATIONAL. ALL RIGHTS RESERVED.
