# Files and Folders

## Files type

SPAT uses 3 different file types:

* .json
* .ioconfig
* .reverbPresets

*.json* are the main files of  _SPAT Revolution_: sessions are saved in this file type.

To save a session, click on the "Save session" button on the Setup page, or use the shortcut ```Ctrl + S``` on Windows, or ```Cmd + S``` on Mac, on any page of  _SPAT Revolution_.

User-created custom speaker arrangement(s) can be exported or imported as *.ioconfig* files in the edit speaker config window.

Reverb preset can be stored and exported as *.reverbPresets.* They can later be imported back into a session.

## Preferences and resources files

On macOS, preferences are located in:

```Users/.../Library/Application Support/FLUX```

```Users/.../Library/ApplicationSupport/Ircam```

On Windows, there are located in:

```Users/.../AppData/Local/FLUX```

```Users/.../AppData/Local/Ircam```


:::{.callout-note}
Before the 2024.04 release, these folders were located in:
```Users/.../Documents/FLUX SE```
```Users/.../Documents/Ircam```
:::

The FLUX folder contains a subfolder named *Config*  which has 3 files:

* .ioconfig contains your added speaker arrangements to  _SPAT Revolution_
* .presets contains your reverb presets
* .theme contains your theme (Dark or Light mode)

A subfolder named *Preferences* containing:

*  hrtf.json file which includes your HRTFs files location
*  users.json contains your saved software preferences
*  Preferences.xml saves some paths
*  UI.xml saves your user interface preferences
*  Property Memory subfolder contains the memory slots saved by parameters

A subfolder named *Shell* containing:

*  history.txt - a history of the terminal commands

The FLUX - IRCAM Folder contains preferences and presets of the three _SPAT Revolution_ plug-ins.

The Ircam Folder contains a subfolder called *sofa* which contains the sofa.catalog.xml file. The HRTF catalog.

:::{.callout-note}
*When backing up a system, make sure to copy all these folders to secure the complete software configuration.*
:::

## Path for Recorded Audio Files

Audio files are recorded in the directory of your session, in a folder named "SessionName_media", SessionName replaced by the name of the SPAT session name.
To be noted, if the session is in a folder of the same name, the folder for the audio is "Media" (no need to be documented, only for internal information).
Audio is recorded in wave Riff64, 32-bit float, interleaved. All inputs will be recorded in one unique file. For the other blocks, a single file will be created for each block, with the following name convention: "Blocktype blockname (format) - recordNumber.wav". For example, for a room named "WFS" in the format "Frontal Line 5", it will be "Room WFS (Frontal Line 5) - 0001.wav"
This is not a broadcast wave for now, the recording has no timestamp.

:::{.callout-note}
A first file is created when arming a file to prevent CPU spike at the recording start. It will be deleted when de-arming the blocks or closing the session.
:::

## Paths for python script

```Users/.../Desktop```

```Users/.../Document/FLUX/Spat Revolution```

:::{.callout-note}
*An example of a script file is the [customSpeakerArrangement](https://public.3.basecamp.com/p/rQStK3igPkaXisYS4Gs5sJ2g/upload/download/customSpeakerArrangement.py?disposition=attachment) that can be used as a method to add arrangements to  _SPAT Revolution_.*
:::