# Transaural

Although we said earlier that binaurally encoded files are not compatible with stereo loudspeaker systems, it turns out that in _SPAT Revolution_ there is a way to play binaurally encoded signals on loudspeakers if necessary. You can do this by transcoding a binaural stream into a Transaural stream either at the _Input Transcoder_ stage or at the _Master Transcoder_ stage of the **Setup** page graph.

The term _Transaural_ refers only to the transcoding of binaural signals into loudspeaker-compatible signals. The reproduction mode is also known as "cross-talk cancellation" as it uses this very process to establish the loudspeaker-compatible signals.

:::{.callout-warning}
 To successfully achieve cross-talk cancellation, it is assumed that the listener _will be placed at a particular position with respect to the loudspeaker pair_, or the spatial information will not be properly perceived. The loudspeaker pair need to be positioned as a regular stereo setup, Left at -30 degrees and Right at +30 degrees.
:::

An optimum listening position such as that needed for Transaural decoding, is also known as the _Sweet Spot_ (see [_Listener Position_ -@listener-position]). It is a fundamental concept to be aware of as we move into the next section: _Channel Based_ streams and panning algorithms.
