# Spatialization Technology

In this section, we will discuss on the various spatialization tool used by _SPAT Revolution_.

Here are some straight to the point key points:

+ _SPAT Revolution_ is an object-based audio engine. The mixes you will create will consist in sets of data for each sound object. These data sets will then be decoded for a certain type of spatialization technique.

:::{.callout-note}
With _SPAT Revolution_ **Ultimate** license, several render can be done at the same time (multi-room).
:::

+ Thanks to the object-based engine, you can create sound stages in all spatialized audio format possible: channel-based, ambisonics (up to seventh order), binaural and transaural. If these names does not ring a bell to you, do not fear, we will cover these different techniques later in this section.
+ On top of the object-based engine, _SPAT Revolution_ also covers the acoustic simulation side of things. The build-in reverberation will adapt to your mixes, and, more importantly, to your desired output format.
+ _SPAT Revolution_ aims at many use cases, many of them being for live performances. It was designed to not add any more latency than necessary on the signal path.

Let's start with an important notion of spatial audio: the listener position.

<!-- TODO : NEED PICTURE HERE -->
