# Users and Applications

_SPAT Revolution_ is aimed at all practitioners working in the medium of spatial audio and 3D sound production - old and new. It is an expert system intended for professional use but its intuitive graphical interface invites a more diverse range of creators to engage in spatial sound production - if it is your first experience working with spatial sound technology, _SPAT Revolution_ is a great way to start out directly at a professional quality level.

_SPAT Revolution_ spatialises and renders audio in real-time. It is used in:

- post-production for film
- studio composition
- concert diffusion
- virtual reality
- audio for video games
- 360 video soundtracks
- 3D Audio for broadcast
- interactive sound art
- live production mixing
- scientific research and development
- sound design for film, music and theatre
- environmental sound

In the contexts of live production or sound installation, the composer or sound mixer can associate sound events with a room effect or a specific position in space. Virtual objects can be controlled on screen, or by a sequencer, a score-following system, or any other algorithmic approach. Spat can easily be linked to any remote control device (show controllers, trajectory applications, tracking systems, tablet, smartphone, joystick, gestural sensors, etc.) through OSC and RTTrPM interfacing protocols. _RTTrPM is supported by the _SPAT Revolution_ **Ultimate** license only._

In the contexts of studio mixing and post-production, a virtual source/object can receive its audio from individual channels on a mixing desk or DAW with additional controllers easily set up to allow hands on control of the positions and characteristics of virtual sources and associated room effect. _SPAT Revolution_ can re-mix a multichannel mix from one format in a virtual room that could be rendered in a different output format, allowing a novel approach to up- and down-mixing.

In the context of Augmented and Virtual Reality, a spatialized auditory component is essential in creating the sensations of presence and immersion in interactive virtual reality applications. In such scenarios, the B-Format and binaural 3D capabilities of Spat are particularly well suited.

An important thing to keep in mind is the long heritage and technical expertise behind _SPAT Revolution_. There are many critical factors to consider when multichannel audio is actually applied in the real world. But rest assured that the algorithms behind your spatial sound project are being implemented correctly at the stage of the authoring and rendering environment. It is good to know that _SPAT Revolution_ is built with such a high level of technical expertise in such an intuitive package.

> Whatever the scale of your spatialized audio production, _SPAT Revolution_ makes it simple to craft an impressive and reliable end result.
