docSection: "Processing"
docSubsection: ""

project:
  type: book
  output-dir: ../../_build/bittersweet-pro ####### <=========== Don't forget to edit path if renaming is needed. YAML don't support concatenation

book:
  title: "Bittersweet Pro"
  author: "FLUX:: Immersive"
  date: "2/6/2023"
  downloads: [pdf]
  chapters:
    - index.qmd
    - General_Settings.qmd
    - Geek.qmd
    - Plugin_Settings.qmd
    - Preset_Management.qmd
    - Preset_Manager.qmd
    #- Measurements.qmd
    - Specification.qmd

#[Release Notes](../../flux_processing_release_notes.md)


format:
  html:
    theme: cosmo
    default-image-extension: gif
  pdf:
    documentclass: scrreport
    default-image-extension: png