project:
  type: book
  output-dir: ../../_build/bittersweet-pro

book:
  title: "Bittersweet Pro"
  chapters:
    - index.qmd
    - General_Settings.qmd
    - Geek.qmd
    - Plugin_Settings.qmd
    #- Measurements.qmd
    - text: Preset Management
      href: ../generic_Preset_Management.qmd
    - text: Preset Manager
      href: ../generic_Preset_Manager.qmd
    - text: Specifications
      href: ../generic_specifications.qmd
    - Credits.qmd
  appendices:
    - ../flux_processing_release_notes.qmd

metadata-files: 
  - ../_common.yaml