project:
  type: book
  output-dir: ../../_build/syrah ####### <=========== Don't forget to edit path if renaming is needed. YAML don't support concatenation


book:
  title: "Syrah"
  author: "FLUX:: Immersive"
  date: "2/6/2023"
  downloads: [pdf]
  chapters:
  - index.qmd
  - Introduction.qmd
  - User_Interface.qmd
  - Input_Output_Section.qmd
  - Processing_Section.qmd
  - Metering_Section.qmd
  - Preset_Management.qmd
  - Plug-in_Settings.qmd
  - Get_started.qmd
  - Specifications.qmd
  appendices:
    - ../flux_processing_release_notes.qmd
    
format:
  html:
    theme: cosmo
    default-image-extension: gif
  pdf:
    documentclass: scrreport
    default-image-extension: png
    include-in-header: ../fluxtemplate.tex
