project:
  type: book
  output-dir: ../../_build/syrah

book:
  title: "Syrah"
  author: "FLUX:: Immersive"
  date: "2/6/2023"
  downloads: [pdf]
  chapters:
  - index.qmd
  - Introduction.qmd
  - User_Interface.qmd
  - Input_Output_Section.qmd
  - Processing_Section.qmd
  - Metering_Section.qmd
  - Plug-in_Settings.qmd
  - Get_started.qmd
  - text: Preset Management
    href: ../generic_Preset_Management.qmd
  - text: Preset Manager
    href: ../generic_Preset_Manager.qmd
  - text: Specifications
    href: ../generic_specifications.qmd
  - Credits.qmd
  appendices:
    - ../flux_processing_release_notes.qmd
    
metadata-files: 
  - ../_common.yaml