# Display

## Eq Display (12)
Graphical editing of the three-band Detector EQ is provided. Double click on the EQ display will expand it.

## Input Level Meter (13)
Vu-meter, not peak-meter, referenced to -16 dB Fs by default, with auto scale depending of the threshold values.

When the MS Width section is engaged, the M (Mid) level is displayed on the left meter. S (Side) is displayed on the 
right meter. The green index reflects the threshold value.

## Output Level Meter (14)
Vu-meter, not peak-meter, referenced to -16 dB Fs by default, with auto scale depending of the threshold values.

When the MS Width section is engaged, the M (Mid) level is displayed on the left meter. S (Side) is displayed on 
the right meter.

## Resultant Envelope (15)
Vu-meter, not peak-meter, referenced to -16 dB Fs by default.  
The scale is +/- 12 dB.  
This is the compression, de-compression, expander and de-expander summing envelope.

## Dynamic difference between in and out (16)
Vu-meter, not peak-meter, referenced to -16 dB Fs by default.  
The scale is +/- 12 dB.

## Level difference between in and out (17)
Vu-meter, not peak-meter, referenced to -16 dB Fs by default.  
The scale is +/- 12 dB.  This is the compression, de-compression, expander and de-expander summing envelop which 
also takes account of the input and output gains of the band.

## Dynamic Activity Display (18)
No scale  
Two green lines on the Dynamic Activity display reflect the current L.I.D. Threshold value.  
For Compressor and DCompressor sections, the L.I.D. action is effective only when the orange Dynamic Activity 
exceeds the area between the two green lines.  For Expander and DExpander sections, the L.I.D. action is effective 
only when the orange Dynamic Activity () stays inside the area between the two green lines.

## Instant Release Value (19)
Auto Scale depending of the release value(s)

## Resulting Transfer Curve (11)
Auto Scale depending of the threshold value(s)
