on:
  workflow_dispatch:
  push:
    branches:
      - master

name: Quarto Publish

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.3.235
          tinytex: true

      - name: Render all Quarto projects
        env:
          QUARTO_PRINT_STACK: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # run: |
        #   for d in "[a-z][a-z]_[A-Z][A-Z]/*/"
        #   do
        #     echo "Rendering $d ..."
        #     quarto render "$d"
        #   done
        #   echo "QUARTO_OUTPUT=_build" >> $GITHUB_ENV
        run: |
          echo "QUARTO_OUTPUT=_build" >> $GITHUB_ENV
          quarto render en_US/home
        shell: bash

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: _build
          path: _build

  Deploy-Production:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: _build
          path: _build
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      # - name: Build Project Artifacts
      #   run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
