on:
  workflow_dispatch:
  push:
    branches:
      - master

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.3.235
          tinytex: true

      - name: Render all Quarto projects
        env:
          QUARTO_PRINT_STACK: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for d in "[a-z][a-z]_[A-Z][A-Z]/*"
          do
            echo "Rendering $d ..."
            quarto render "$d"
          done
          echo "QUARTO_OUTPUT=_build" >> $GITHUB_ENV
        shell: bash

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build