project:
  type: book
  output-dir: ../../_build/stereotool ####### <=========== Don't forget to edit path if renaming is needed. YAML don't support concatenation

book:
  title: "Stereo Tool"
  author: "FLUX:: Immersive"
  date: "2/6/2023"
  downloads: [pdf]
  chapters:
  - index.qmd
  - Credits.qmd
  appendices:
    - ../flux_processing_release_notes.qmd

metadata-files: 
  - ../_common.yaml